### ISSUE TITLE
Server down?

### ISSUE THREAD

**Issue by ateymour** [surhud004/Foodish#16]
It seems like the page is down? Requests are bouncing and the landing page leads to an error:

![image](https://user-images.githubusercontent.com/19393570/205529254-c96aa950-4b2a-4f04-986c-69b96742d5c5.png)

**Comment by Huasito-Appel** [comment]
Looks like still down

**Comment by Elliot-Evans-95** [comment]
Was about to use this for an example app and its still here as of time of writing

**Comment by circularsprojects** [comment]
i have my own instance of foodish hosted on https://circulars.dev/foodish
use it as much as you want

**Comment by surhud004** [comment]
A new version of the Foodish API v2 has been released! Read more: https://github.com/surhud004/Foodish/discussions/19
