### ISSUE TITLE
Application Error 

### ISSUE THREAD

**Issue by carolineablynch** [surhud004/Foodish#2]
Hi Team! I'm seeing your application is having the error below when i use it in my application: 

Access to XMLHttpRequest at 'https://foodish-api.herokuapp.com/api/' from origin 'https://carolineablynch.github.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

additionally, I'm seeing https://foodish-api.herokuapp.com/ has an application error when you run the link.

**Comment by surhud004** [comment]
Hi @carolineablynch,
Unfortunately, this app is running on a free Heroku dyno. Please try accessing it on or after January 1st, 2021.
We are trying to resolve this issue as soon as possible.
We apologize for the inconvenience caused.
Happy Coding and Happy Holidays!

**Comment by surhud004** [comment]
Issue resolved for now.
