### ISSUE TITLE
Image size

### ISSUE THREAD

**Issue by Aman-8955** [surhud004/Foodish#21]
Hy @surhud004 ,
I see the web page of foodish. i saw the issue is the image that is generated by api is not in fix size to show on web its look not good if we fix its size then it will be better in user experience so,
can you assign it to me i want to add some basic design related stuff.

**Comment by surhud004** [comment]
Hey @Aman-8955 this feature sounds good, I am assigning this issue to you, please fork this repo and create a PR whenever ready. Thanks!
