### ISSUE TITLE
https://foodish-api.herokuapp.com/

### ISSUE THREAD

**Issue by curaunt** [surhud004/Foodish#6]
API not accessible 
when visiting the above link I get an "application error"

**Comment by surhud004** [comment]
Hi @curaunt,
Unfortunately, this app is running on a free Heroku dyno, therefore, the API seemed to be broken and displayed the `application-error`. Apologies.

**Comment by surhud004** [comment]
API uptime - checked ✔️ 
Issue resolved for now.
