### ISSUE TITLE
It can't be used now

### ISSUE THREAD

**Issue by Basin-Bug** [surhud004/Foodish#9]
This API has a 503 error so that It can't use for get some foodish pictures. Would you like to fix about this server?

**Comment by surhud004** [comment]
Hi @Basin-Bug,
Unfortunately, this app is running on a free Heroku dyno, therefore, the API returns 503 and displays the `application-error` message. Apologies. It will be up and running as expected on the first of the next month.

**Comment by Basin-Bug** [comment]
Thank you and I think it can be used now!

**Comment by surhud004** [comment]
API uptime - checked ✔️
Issue resolved for now.

**Comment by surhud004** [comment]
Known server limit issue. Read more at https://github.com/surhud004/Foodish/wiki#server-limit-issue
